services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: sqladmin
      POSTGRES_PASSWORD: sqladmin123
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data: